---
title: "GridWork"
author: "Pete Way"
date: "5/22/2019"
output: pdf_document
---

```{r}
gridblockRoads = read.csv("../Excel & CSV Sheets/Grid Layout Test Files/GridCountRoads.csv")
names(gridblockRoads) <- c("Grid_Block", "Road_Count")
gridblockRoads

griddata = read.csv("../Excel & CSV Sheets/Grid Layout Test Files/Grid Data.csv")
griddata = griddata[which(griddata$Accident=='1'),]
gridtable = table(griddata$Grid_Block)
gridtable = as.data.frame(gridtable) 
names(gridtable) <- c("Grid_Block", "Accident_Count")
sortedblocks <- gridtable[order(-gridtable$Accident_Count),]
colnames(gridtable)

merged = merge(gridblockRoads,sortedblocks)
merged
mergedSort <- merged[order(-merged$Accident_Count),]
mergedSort
hist(merged$Road_Count, xlab="Number of Roads in Block",main="Distribution of Roadways", col='lightblue')
hist(merged$Accident_Count, xlab="Number of Accidents in Block", main="Number of Accidents per Block", col="coral")
plot(merged$Road_Count,merged$Accident_Count, xlab="Number of Roads", ylab="Number of Accidents")
cor(mergedSort)

library(corrplot)
cormerged = cor(merged)
corrplot(as.matrix(cormerged))
```



```{r}

```
