---
title: "Mapping"
author: "Pete Way"
date: "October 2, 2019"
output: pdf_document
---

```{r}

accidentcounts = read.csv("/Users/Pensi/Downloads/Grid_Block_Count.csv")

library(dplyr)
byblock = accidentcounts %>% group_by(Block) %>% summarise(Count = sum(Count))
```


```{r}
dayframe1hours = c(0,1,2,3,4,19,20,21,22,23)
dayframe2hours = c(5,6,7,8,9)
dayframe3hours = c(10,11,12,13)
dayframe4hours = c(14,15,16,17,18)
```

```{r}
library(dplyr)
dayframe1 = accidentcounts %>%
      filter(accidentcounts$Hour %in% dayframe1hours)

dayframe1 = dayframe1 %>% group_by(Block) %>% summarise(Count = sum(Count))

dayframe2 = accidentcounts %>%
      filter(accidentcounts$Hour %in% dayframe2hours)

dayframe2 = dayframe2 %>% group_by(Block) %>% summarise(Count = sum(Count))

dayframe3 = accidentcounts %>%
      filter(accidentcounts$Hour %in% dayframe3hours)

dayframe3 = dayframe3 %>% group_by(Block) %>% summarise(Count = sum(Count))
      
dayframe4 = accidentcounts %>%
      filter(accidentcounts$Hour %in% dayframe4hours)

dayframe4 = dayframe4 %>% group_by(Block) %>% summarise(Count = sum(Count))
```



```{r}
nohw = read.csv("E:/Work/model_GF50-50_NoHighway_Forecast.csv")
hw = read.csv("E:/Work/model_GF50-50_Highway_Forecast.csv")
grid = read.csv("E:/Work/CenterPoints.csv")
hw$Latitude <- grid$Latitude[match(hw$Grid_Block, grid$Grid_Block)]
hw$Longitude <- grid$Longitude[match(hw$Grid_Block, grid$Grid_Block)]

nohw$Latitude <- grid$Latitude[match(nohw$Grid_Block, grid$Grid_Block)]
nohw$Longitude <- grid$Longitude[match(nohw$Grid_Block, grid$Grid_Block)]
```

```{r}
library(lubridate)
# acc = read.csv("E:/Work/2_4_2018_Accidents.csv")

acc1718 = read.csv("E:/Work/2017+2018 Accidents.csv")
acc19 = read.csv("E:/Work/2019 Accidents.csv")

colnames(acc1718)[colnames(acc1718)=="Center_Long"] <- "Longitude"
colnames(acc1718)[colnames(acc1718)=="Center_Lat"] <- "Latitude"
keep = c("Latitude", "Longitude", "Unix", "Grid_Block", "humidity", "DayFrame")
acc1718 = acc1718[(keep)]

library(feather)
testing = read_feather("E:/Work/2019 Weather.feather")
acc19$Match = paste(acc19$Grid_Block, acc19$Unix)
colnames(testing)
testing$Match = paste(testing$ORIG_FID, testing$time)
colnames(acc19)
acc19$humidity = testing$humidity[match(acc19$Match, testing$Match)]
acc19 = acc19[(keep)]
allacc = rbind(acc1718, acc19)

rm(acc1718, acc19, acc1718test, hw, hwframe, hwmap, nohw, nohwframe, noprec, noprecframe, bb, cda, frame, hwtitle, keep, keeps, lats, lons, nohwtitle, prectitle)
```

```{r}
library(ggmap)
# frame=1
accframe = acc
# accframe = allacc[(allacc$DayFrame == frame), ]
lats<-c(34.99, 35.15)
lons<-c(-85.4,-85.05)
title = paste("E:/Work/Maps/Accidents-Dayframe",frame,".png", sep="")
png(title, width=12,height=6,units='in', res=600)
par(mar = rep(0, 4))
bb<-make_bbox(lon=lons,lat=lats, f=0.05)
calc_zoom(bb)
# bb<-make_bbox(lon=lons,lat=lats,f=0.05)
cda<-get_map(bb,zoom=11, source='stamen',maptype="watercolor")
ggmap(cda, legend = "bottom")+theme_minimal(base_size = 22) +
  labs(x="",y="", title=paste("Accidents in Chattanooga - Dayframe ", frame, sep="")) +
stat_density2d(data = accframe, aes(x = Longitude, y = Latitude, fill = ..level.., alpha = ..level..), geom = "polygon", size = 0.01, bins = 50) +
scale_fill_gradient(low = "purple", high = "orange", name = "Accidents", breaks = c(1,70,140), labels = c(1,70,140), limits=c(1,140)) +
scale_alpha(range = c(0, .3), guide = FALSE)
dev.off()
```

```{r}
library(ggmap)
lats<-c(34.99, 35.15)
lons<-c(-85.4,-85.05)
title = paste("E:/Work/Maps/Accidents.png", sep="")
png(title, width=12,height=6,units='in', res=600)
par(mar = rep(0, 4))
bb<-make_bbox(lon=lons,lat=lats, f=0.05)
calc_zoom(bb)
# bb<-make_bbox(lon=lons,lat=lats,f=0.05)
cda<-get_map(bb,zoom=11, source='stamen',maptype="watercolor")
ggmap(cda, legend = "bottom")+theme_minimal(base_size = 22) +
  labs(x="",y="", title="Accidents in Chattanooga") +
stat_density2d(data = allacc, aes(x = Longitude, y = Latitude, fill = ..level.., alpha = ..level..), geom = "polygon", size = .00001, bins = 200)+ scale_fill_gradient(low = "purple", high = "orange", name = "Accidents", breaks = c(20,150,300), labels = c(20,150,300), limits=c(20,300)) +
scale_alpha(range = c(0, .2), guide = FALSE)
dev.off()
```

```{r}
tab = table(allacc$Grid_Block)
tab = as.data.frame(tab)
colnames(tab) = c("Grid_Block", "Count")
colnames(testing)
tab$Latitude <- testing$Center_Lat[match(tab$Grid_Block, testing$ORIG_FID)]
tab$Longitude <- testing$Center_Long[match(tab$Grid_Block, testing$ORIG_FID)]
colnames(tab)
head(tab)

tab = tab[(tab$Count>20), ]
lats<-c(34.99, 35.15)
lons<-c(-85.4,-85.05)
title = paste("E:/Work/Maps/AccidentCount",frame,".png", sep="")
png(title, width=12,height=6,units='in', res=600)
par(mar = rep(0, 4))
bb<-make_bbox(lon=lons,lat=lats, f=0.05)
calc_zoom(bb)
# bb<-make_bbox(lon=lons,lat=lats,f=0.05)
cda<-get_map(bb,zoom=11,maptype="watercolor", source='stamen')
ggmap(cda, legend = "bottom")+theme_minimal(base_size = 22)+
  labs(x="",y="", title="") +
  geom_point(aes(x=tab$Longitude, y=tab$Latitude, color = tab$Count), data=tab, alpha = .5, size=5) + scale_color_gradient(low = "yellow", high = "red", name = "Accidents", breaks = c(20,600,1110), labels = c(20,600,1110), limits=c(20,1110)) + theme(axis.text.x = element_blank(), axis.text.y = element_blank())
dev.off()
```

```{r}
high = allacc[(allacc$Grid_Block==851), ]
```


```{r}
colnames(hw)
nohw = nohw[(nohw$Prediction==1), ]
hw = hw[(hw$Prediction==1),]

nohw = nohw[(nohw$Probability>.7), ]
hw = hw[(hw$Probability>.7),]


library(ggmap)
frame = 4
nohwframe = nohw[(nohw$DayFrame == frame), ]
hwframe = hw[(hw$DayFrame == frame),]
accframe = acc[(acc$DayFrame == frame),]
lats<-c(34.99, 35.15)
lons<-c(-85.4,-85.05)
hwtitle = paste("E:/Work/Maps/Highway",frame,".png", sep="")
png(hwtitle, width=12,height=6,units='in', res=600)
par(mar = rep(0, 4))
bb<-make_bbox(lon=lons,lat=lats, f=0.05)
calc_zoom(bb)
# bb<-make_bbox(lon=lons,lat=lats,f=0.05)
cda<-get_map(bb,zoom=11,maptype="watercolor", source='stamen')
ggmap(cda, legend = "bottom")+theme_minimal(base_size = 22)+
  labs(x="",y="", title="Accidents in Chattanooga - Highway Model") +
  geom_point(aes(x=hwframe$Longitude, y=hwframe$Latitude, color=hwframe$Probability), data=hwframe, alpha = .75, size=5, name="Probability") + geom_point(aes(x=accframe$Longitude, y=accframe$Latitude), data=accframe, color='red', alpha = 1)

dev.off()

 nohwtitle = paste("E:/Work/Maps/NoHighway",frame,".png", sep="")
png(nohwtitle, width=12,height=6,units='in', res=600)
  ggmap(cda, legend = "bottom") +theme_minimal(base_size = 22)+
  labs(x="",y="", title="Accidents in Chattanooga - No Highway Model") +
  geom_point(aes(x=nohwframe$Longitude, y=nohwframe$Latitude, color=nohwframe$Probability), data=nohwframe, alpha = .75, size=5) + geom_point(aes(x=accframe$Longitude, y=accframe$Latitude), data=accframe, color='red', alpha = 1)
dev.off()
```

```{r}
# noprec = read.csv("E:/Work/model_GF50-50_HighwayNoPrecip_Forecast.csv")
# noprec = noprec[(noprec$Prediction==1), ]
# noprec = noprec[(noprec$Probability>.7), ]
# noprec$Latitude <- grid$Latitude[match(noprec$Grid_Block, grid$Grid_Block)]
# noprec$Longitude <- grid$Longitude[match(noprec$Grid_Block, grid$Grid_Block)]
library(ggmap)
frame = 1
noprecframe = noprec[(noprec$DayFrame == frame), ]
accframe = acc[(acc$DayFrame == frame),]
prectitle = paste("E:/Work/Maps/NoPrec",frame,".png", sep="")
png(prectitle, width=12,height=6,units='in', res=600)
par(mar = rep(0, 4))
bb<-make_bbox(lon=lons,lat=lats, f=0.05)
calc_zoom(bb)
# bb<-make_bbox(lon=lons,lat=lats,f=0.05)
cda<-get_map(bb,zoom=11,maptype="watercolor", source='stamen')
ggmap(cda, legend = "bottom")+theme_minimal(base_size = 22) +
  labs(x="",y="", title="Accidents in Chattanooga - No Prec. Inten.") +
  geom_point(aes(x=noprecframe$Longitude, y=noprecframe$Latitude, color=noprecframe$Probability), data=noprecframe, alpha = .75, size=5) + geom_point(aes(x=accframe$Longitude, y=accframe$Latitude), data=accframe, color='red', alpha = 1)

dev.off()
```

