---
title: "ChattaVERSUS911"
output: pdf_document
---
##Comparison of Chatta Data and 911 Accidents
```{r}
acc_Chatta = read.csv("/Users/peteway/Documents/GitHub/SCAL_USIgnite-911/Excel & CSV Sheets/ChattaData Accident System/All Accidents.csv")
acc_911 = read.csv("/Users/peteway/Documents/GitHub/SCAL_USIgnite-911/Excel & CSV Sheets/Accidents/2017-2019 Accidents No Dups Take 4.csv")
acc_911$Date[0:5]
library(lubridate)
acc_Chatta$Hour = hour(acc_Chatta$Incident.Date)
acc_911$Hour = hour(hms(acc_911$Time))

library(lubridate)
# acc_Chatta$Date = as.Date(as.POSIXct(acc_Chatta$Unix, origin="1970-01-01"))
acc_Chatta$Year = year(as.Date(acc_Chatta$Incident.Date))
acc_Chatta$Date = date(acc_Chatta$Incident.Date)

test_Chatta = acc_Chatta[acc_Chatta$Year == 2018 , ]
tab_Chatta = table(test_Chatta$Date, test_Chatta$Hour)
tab_Chatta = as.data.frame(tab_Chatta)
names = c("Date","Hour","Count")
colnames(tab_Chatta) = names
```

###Adding in the Missing Dates for the 911 data 
```{r}
# acc_911$Date = as.Date(acc_911$Date))
acc_911$Year = year(acc_911$Date)
unique(acc_911$Year)

test_911 = acc_911[acc_911$Year == 2018 , ]
unique(test_911$Year)
length(unique(test_911$Date))
tab_911 = table(test_911$Date, test_911$Hour)
# unique(tab_911$Date)

tab_911 = as.data.frame(tab_911)
colnames(tab_911) = names
tab_911$Year = year(tab_911$Date)
tab_911 = tab_911[tab_911$Year == 2018 , ]
library(tidyr)
library(dplyr)

test <- merge(tab_Chatta, tab_911, by = c("Date","Hour"), all.x = TRUE)

##Replace NAs with zeroes!
test[is.na(test)] <- 0
```

```{r}

colnames(test) = c("Date","Hour","Count_Chatta","Count_911", "Year")

test2 = test[0:30,]
# png("AccidentsBySource.png", width=8,height=4,units='in', res=600)
dev.new(width = 800, height = 400, unit = "px")
par(mar = c(3,3,1,0.1))
plot(test2$Count_911, col='blue',xlab="",lwd=1, type="l", ylab="Accident Count in Data", xaxt="none",yaxt="none", ylim=c(0,130), main="Accidents by Source - January")
lines(test2$Count_Chatta, type="l", col='red', lwd=1)
axis(2, seq(0,300,by=50), seq(0,300,by=50), cex.axis = .7, las=2)
axis.Date(1, seq.Date(as.Date(head(test2$Date, n=1)), as.Date(tail(test2$Date, n=1)), by="week"), las=2)
legend("topleft", legend=c("911", "ChattaData"),
       col=c("blue", "red"), lty=1:1,lwd=2:2, cex=.8)
# dev.off()
```

```{r}
dev.new(width = 800, height = 400, unit = "px")
par(mar = c(3,3,1,0.1))
plot(test$Count_911, col='blue',xlab="",lwd=1, type="l", ylab="Accident Count in Data", xaxt="none",yaxt="none", ylim=c(0,8),xlim=c(0,72), main="Accidents by Source - January 1 - 3")
lines(test$Count_Chatta, type="l", col='red', lwd=1)
axis(2, seq(0,300,by=50), seq(0,300,by=50), cex.axis = .7, las=2)
legend("topleft", legend=c("911", "ChattaData"),
       col=c("blue", "red"), lty=1:1,lwd=2:2, cex=.8)
```

```{r}
tabDate_Chatta = table(test_Chatta$Date)
tabDate_Chatta = as.data.frame(tabDate_Chatta)
names = c("Date","Count")
colnames(tabDate_Chatta) = names


tabDate_911 = table(test_911$Date)
tabDate_911 = as.data.frame(tabDate_911)
colnames(tabDate_911) = names
tabDate_911$Year = year(tabDate_911$Date)
tabDate_911 = tabDate_911[tabDate_911$Year == 2018 , ]
library(tidyr)
library(dplyr)

DateTable <- merge(tabDate_Chatta, tabDate_911, by = c("Date"), all.x = TRUE)

##Replace NAs with zeroes!
DateTable[is.na(DateTable)] <- 0
colnames(DateTable) = c("Date","Count_Chatta","Count_911","Year")

DateTable$Difference <- abs(DateTable$Count_Chatta - DateTable$Count_911)
```

