---
title: "Testing"
output: pdf_document
---
```{r}
transparent = theme(panel.background = element_rect(fill = "transparent"), # bg of the panel
    plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
    panel.grid.major = element_blank(), # get rid of major grid
    panel.grid.minor = element_blank(), # get rid of minor grid
    legend.background = element_rect(fill = "transparent"), # get rid of legend bg
    legend.box.background = element_rect(fill = "transparent"))
```

```{r}
library(st)
st_write(acc_911, '/Users/peteway/Documents/GitHub/SCAL_USIgnite-911/Excel & CSV Sheets/Shapefiles/New 911 Accident Shapefiles/Accidents_with_Time.shp')
```


```{r}
library(sf)
library(raster)
accidents = st_read('/Users/peteway/Documents/GitHub/SCAL_USIgnite-911/Excel & CSV Sheets/Shapefiles/New 911 Accident Shapefiles/Accidents_Full.shp')
##Drop zero/incorrect lat/longs in this way
# accidents = accidents[-c(77840, 78305, 46778), ]

```

```{r}
library(ggmap)
library(ggplot2)
par(mar = rep(0, 4))

box = st_bbox(accidents)
box
idhere = ''
register_google(idhere)
bb<- make_bbox(lat=c(box['ymin'],box['ymax']),lon=c(box['xmin'],box['xmax']), f=0.05)
bb
zoomed = calc_zoom(bb)
zoomed 

cda<-get_map(bb,zoom=zoomed,maptype="watercolor", source='stamen')
ggmap(cda) + coord_sf(crs = st_crs(accidents)) + 
  geom_sf(data = accidents, size=1, color= "blue" , fill=NA, inherit.aes = FALSE) 

```

```{r}
hexgrid = st_read("/Users/peteway/Documents/GitHub/SCAL_USIgnite-911/Excel & CSV Sheets/Shapefiles/Rework_HexGridpoint2sqmi/Accident_HexGrid_02sqmi.shp")
hexgridinfo = hexgridinfo[, -which(names(hexgridinfo) %in% c('TARGET_FID'))]
hexgrid = merge(hexgridinfo, modes, by="GRID_ID", all.x=TRUE)
hexgrid$geometry <- hexgrid$Center
hexgrid$Center  <- st_centroid(hexgrid$geometry)
colnames(hexgridinfo)

write.csv(hexgrid, "/Users/peteway/Documents/GitHub/SCAL_USIgnite-911/Excel & CSV Sheets/Hex_Grid/HexGridInfoComplete.csv")
st_write(hexgrid, "/Users/peteway/Documents/GitHub/SCAL_USIgnite-911/Excel & CSV Sheets/Shapefiles/Rework_HexGridpoint2sqmi/Accident_HexGrid_Info.shp")

cda<-get_map(gridbb,zoom=gridzoomed,maptype="watercolor", source='stamen')
ggmap(cda) + coord_sf(crs = st_crs(hexgrid)) + 
  geom_sf(data = hexgridinfo, size=1, color= 'black' , fill=NA, inherit.aes = FALSE) +
  geom_sf(data = hexgrid, size=1, color= "red" , fill=NA, inherit.aes = FALSE)
```

##Heatmap for accidents
```{r}
hexgrid1 = hexgrid[(hexgrid$Join_Count > 20),]
hexgridlo = hexgrid1[(hexgrid1$Join_Count < 300),]
hexgridhi = hexgrid[(hexgrid$Join_Count > 300),]

gridbox = st_bbox(hexgrid1)
gridbox
gridbb<- make_bbox(lat=c(gridbox['ymin'],gridbox['ymax']),lon=c(gridbox['xmin'],gridbox['xmax']), f=0.05)
gridbb
gridzoomed = calc_zoom(gridbb)+1

png("/Users/peteway/Documents/GitHub/SCAL_USIgnite-911/Graphs & Images/After Duplicate Rework/LowIntensityHotspots.png", width=9,height=6,units='in', res=600,bg = 'transparent')
ggmap(cda) + coord_sf(crs = st_crs(hexgridlo)) + geom_sf(data=hexgridlo, inherit.aes = FALSE, aes(fill = hexgridlo$Join_Count)) + scale_fill_gradient2(low='darkgrey', mid='yellow', high='red', midpoint=170, limits=c(20,300), "Number of Accidents", breaks=seq(20,300,by=70))  + ggtitle("Accident Hotspots - Low Intensity") + transparent  + xlab("Longitude") + ylab("Latitude")
dev.off()

png("/Users/peteway/Documents/GitHub/SCAL_USIgnite-911/Graphs & Images/After Duplicate Rework/HighIntensityHotspots.png", width=9,height=6,units='in', res=600,bg = 'transparent')
ggmap(cda) + coord_sf(crs = st_crs(hexgridhi)) + geom_sf(data=hexgridhi, inherit.aes = FALSE, aes(fill = hexgridhi$Join_Count)) + scale_fill_gradient2(low='orange', mid='red', high='black', midpoint=800, limits=c(300,1400), "Number of Accidents", breaks=c(seq(300,1400,by=300), 1400)) + ggtitle("Accident Extreme Hotspots") + transparent  + xlab("Longitude") + ylab("Latitude")
dev.off()
# +
  # scale_fill_viridis_c(option = "magma", "# Accidents", limits=c(1,1360)) 

class(hexgrid1)

```

```{r}
colnames(hexgrid1)
hexgridinfo = hexgrid[c('Join_Count','GRID_ID','TARGET_FID','geometry' )]
length(unique(hexgridinfo$GRID_ID))
##Finding the center of the hexgrids
hexgridinfo$Center  <- st_centroid(hexgridinfo$geometry)
cda<-get_map(gridbb,zoom=15,maptype="watercolor", source='stamen')
map = ggmap(cda) + coord_sf(crs = st_crs(hexgridinfo)) + 
  geom_sf(data = hexgridinfo, size=1, color= 'black',fill=NA, inherit.aes = FALSE, legend=TRUE) + transparent + xlab("Longitude") + ylab("Latitude") + labs(caption ="Hexagon Grid covering City of Chattanooga")
# + 
#  geom_sf(data = hexgridinfo$Center, size=1, color= 'red', inherit.aes = FALSE, legend=TRUE)
```

```{r}
library(sf)
library(sp)
library(ggmap)
library(ggplot2)
roads = st_read("/Users/peteway/Downloads/Roadway_Info_Numerical/Roadway_Geometrics_County_HAMILTON.shp")
typeof(roads)
class(roads)

roadbox = st_bbox(roads)
roads = st_transform(roads, "+proj=longlat")
st_crs(roads)

roadbox = st_bbox(roads)
roadbb<- make_bbox(lat=c(roadbox['ymin'],roadbox['ymax']),lon=c(roadbox['xmin'],roadbox['xmax']), f=0.05)
roadzoomed = calc_zoom(roadbb)
roadcda<-get_map(roadbb,zoom=roadzoomed,maptype="watercolor", source='stamen')
ggmap(roadcda) + coord_sf(crs = st_crs(hexgrid)) + 
  geom_sf(data = roads, size=1, color= 'black',fill=NA, inherit.aes = FALSE, legend=TRUE)

cutroads = st_crop(roads, hexgridinfo)

roadbox = st_bbox(cutroads)
roadbb<- make_bbox(lat=c(roadbox['ymin'],roadbox['ymax']),lon=c(roadbox['xmin'],roadbox['xmax']), f=0.05)
roadzoomed = calc_zoom(roadbb)
roadcda<-get_map(roadbb,zoom=roadzoomed,maptype="watercolor", source='stamen')
ggmap(roadcda) + coord_sf(crs = st_crs(cutroads)) + 
  geom_sf(data = cutroads, size=1, color= 'black',fill=NA, inherit.aes = FALSE, legend=TRUE) + 
  geom_sf(data = hexgridinfo, size=1, color= 'red',fill=NA, inherit.aes = FALSE, legend=TRUE) 

```


```{r}
colSums(is.na(cutroads))
drops = c('SPD_LMT' , 'SPD_LMT_S2', 'TRUCK_SPD_','FEAT_WIDTH','SPCL_SY2','SPCL_SYS_2','SPCL_SYS_3')
cutroads = cutroads[, -which(names(cutroads) %in% drops)]

colSums(is.na(cutroads))

hexroads = st_intersection(cutroads, hexgridinfo)

aggregate(NBR_LANES~GRID_ID, data=hexroads, mean)

Mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}
Mode_Lanes = aggregate(NBR_LANES~GRID_ID, data=hexroads, Mode)
Mode_Terrain = aggregate(TY_TERRAIN~GRID_ID, data=hexroads, Mode)
Mode_Class = aggregate(FUNC_CLASS~GRID_ID, data=hexroads, Mode)
Mode_Land = aggregate(LAND_USE~GRID_ID, data=hexroads, Mode)
# aggregate(NBR_LANES~GRID_ID, data=hexroads, max)
# 
# aggregate(NBR_LANES~GRID_ID, data=hexroads, min)

table(Mode_Land$LAND_USE)

modes = merge(Mode_Lanes, Mode_Class, by="GRID_ID")
modes = merge(modes, Mode_Land, by="GRID_ID")
testing = merge(hexgridinfo, Mode_Land, by="GRID_ID", all.x=TRUE)
colSums(is.na(testing))
```

```{r}
roadbox = st_bbox(cutroads)
roadbb<- make_bbox(lat=c(roadbox['ymin'],roadbox['ymax']),lon=c(roadbox['xmin'],roadbox['xmax']), f=0.05)
roadzoomed = calc_zoom(roadbb)
roadcda<-get_map(roadbb,zoom=roadzoomed,maptype="watercolor", source='stamen')
ggmap(roadcda) + coord_sf(crs = st_crs(cutroads)) + 
  geom_sf(data = hexroads, size=1, color= 'black',fill=NA, inherit.aes = FALSE, legend=TRUE) + 
  geom_sf(data = hexgridinfo, size=1, color= 'red',fill=NA, inherit.aes = FALSE, legend=TRUE) 
```


```{r}
library(scales)
max(hexgridinfo$Join_Count)
min(hexgridinfo$Join_Count)
ggplot(hexgridinfo) +
  geom_sf(aes(fill = Join_Count)) +
# + scale_fill_gradient2(low='blue', mid='yellow', high='red', midpoint=175, limits=c(1,1400), "Number of Accidents", oob='red') + 
  scale_fill_viridis_c(option = "magma", "# Accidents", limits=c(0,300)) 

ggplot(hexgridinfo) +
  geom_sf(aes(fill = Join_Count)) +
# + scale_fill_gradient2(low='blue', mid='yellow', high='red', midpoint=175, limits=c(1,1400), "Number of Accidents", oob='red') + 
  scale_fill_viridis_c(option = "magma", "# Accidents", limits=c(300,1400)) 

```

```{r}
# max(testing$TY_TERRAIN)
# min(testing$TY_TERRAIN)
ggplot(testing) +
  geom_sf(aes(fill = TY_TERRAIN)) 

ggplot(testing) +
  geom_sf(aes(fill = NBR_LANES)) 

ggplot(testing) +
  geom_sf(aes(fill = LAND_USE)) 

table(testing$NBR_LANES)

table(testing$FUNC_CLASS)

table(testing$TY_TERRAIN)

table(roadexplain$TYP_FEAT)

roadtype = roadexplain[(roadexplain$TYP_FEAT == 'PAVEMENT'),]
table(roadtype$FEAT_CMPOS)

ggplot(roadtype) + geom_sf(aes(col = FEAT_CMPOS)) 
```

```{r}
write.csv(hexgridinfo, "/Users/peteway/Documents/GitHub/SCAL_USIgnite-911/Excel & CSV Sheets/Hex_Grid/Hex_GridInfo.csv")
```

```{r}
roadexplain = st_read("/Users/peteway/Downloads/Roadway_Info_Raw/Roadway_Geometrics_County_HAMILTON.shp")

table(roadexplain$FUNC_CLASS)

table(roadexplain$TYP_FEAT)

roadexplain = st_transform(roadexplain, "+proj=longlat")
st_crs(roadexplain)

roadbox = st_bbox(roadexplain)
roadbb<- make_bbox(lat=c(roadbox['ymin'],roadbox['ymax']),lon=c(roadbox['xmin'],roadbox['xmax']), f=0.05)
roadzoomed = calc_zoom(roadbb)
roadcda<-get_map(roadbb,zoom=roadzoomed,maptype="watercolor", source='stamen')
ggmap(roadcda) + coord_sf(crs = st_crs(roadexplain)) + 
  geom_sf(data = roadexplain, size=1, color= roadexplain$FUNC_CLASS,fill=NA, inherit.aes = FALSE, show.legend=TRUE)

```

```{r}

hexgridinfo$Grid_Num = seq.int(nrow(hexgridinfo))

city = st_read("/Users/peteway/Documents/GitHub/SCAL_USIgnite-911/Excel & CSV Sheets/Shapefiles/Chattanooga City Limits/Chattanooga.shp")

accident_city = st_crop(accidents, city)

accident_city = st_intersection(accident_city, hexgridinfo)
```

