---
title: "InterstateWork"
output: pdf_document
---

```{r}
library(sf)

# inter = st_read("Interstates/Interstates.shp")
# HW153 = st_read("153/153.shp")
# keep = c("MSLINK","BLM","ELM","ID_NUMBER", "SPD_LMT","geometry")
# HW153 = HW153[(keep)]
# inter = inter[(keep)]
# interstates = rbind(inter, HW153)
# rm(inter, HW153)
library(raster)
# st_write(interstates,'interstates.shp')
interstates = st_read("interstates.shp")

acc_shapes = read.csv("ChattaDataAccidentsComplete.csv")

class(interstates)
class(acc_shapes)
```

```{r}
library(sf)
keepcols = c("Date", "Hour","Unix","Latitude","Longitude")
acc_shapes = acc_shapes[(keepcols)]
rm(keepcols,keep)
coordinates(acc_shapes)=~Longitude+Latitude
geo.prj <- "+proj=longlat" 
proj4string(acc_shapes)<- CRS(geo.prj)
interstates <- st_transform(interstates, CRS(geo.prj)) 
interstates <- st_transform(interstates, CRS(geo.prj)) 
library(raster)
shapefile(acc_shapes, filename='acc_shapes.shp', overwrite=TRUE)
acc_shapes = st_read('acc_shapes.shp')
```

```{r}
library(sf)
library(sp)

st_crs(acc_shapes)
st_crs(interstates)
st_bbox(acc_shapes)
st_bbox(interstates)
```



```{r}
library(sp)
library(sf)
library(ggmap)
library(ggplot2)
# buffing = st_buffer(interstates, dist=.0002)
buffing = bufferzone
# buffing
##Small Lat/LongsY
lats<-c(35,35.01)
lons<-c(-85.22, -85.2)
#Big Lat/Longs
# lats=c(35.01,35.035)
# lons=c(-85.32, -85.22)

par(mar = rep(0, 4))
# bb<- make_bbox(lon=lons,lat=lats, f=0.05)
# zoomed = calc_zoom(bb)

ggplot() + 
  geom_sf(data = buffing, size=1, color= "blue" ) + 
  geom_sf(data = acc_shapes, size =1, color="black") +
  geom_sf(data = interstates, size = 1, color = "red") +
  coord_sf(ylim=lats, xlim=lons) + 
  ggtitle("Accidents along 75 24 Split")

# png("MapofBuffer.png", width=8,height=4,units='in', res=300)
par(mar = rep(0, 4))
bb<- make_bbox(lon=lons,lat=lats, f=0.05)
zoomed = calc_zoom(bb)
# bb<-make_bbox(lon=lons,lat=lats,f=0.05)
cda<-get_map(bb,zoom=15,maptype="watercolor", source='stamen')
ggmap(cda) + coord_sf(crs = st_crs(interstates)) + 
  geom_sf(data = buffing, size=1, color= "blue" , fill=NA, inherit.aes = FALSE) + 
  geom_sf(data = acc_shapes, size =1, color="black", inherit.aes = FALSE) +
  geom_sf(data = interstates, size = 1, color = "red", inherit.aes = FALSE) + ggtitle("Accidents along I-75")
# dev.off()
```

