---
title: "ReCreating Graphs"
output: pdf_document
---

```{r}
accidents = read.csv("../Excel & CSV Sheets/AllAccidents.csv")
#0 is Sunday in R land!!
accidents$Weekday = as.POSIXlt(accidents$Date)$wday
tab = table(accidents$Hour, accidents$Weekday)
tab = as.data.frame.matrix(tab) 

names(tab) = c('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday')

png("../Graphs & Images/Basic Layouts/AllAccidentsWeekdayHourSplit.png", width=10,height=6,units='in', res=600)
plot(tab$Sunday, type="l", ylim=c(0,1000),col='pink', lwd=4, ylab="Number of Accidents", xlab="Hour of Day", xlim=c(.5,24.5), xaxt="none", yaxt="none",main="Accidents by Weekday and Hour")
axis(1, c(1,7,13,19,24), c(0,6,12,18,23),las="2")
axis(2,las="2")
lines(tab$Monday, col='red', lwd=4)
lines(tab$Tuesday, col='orange', lwd=4)
lines(tab$Wednesday, col='yellow', lwd=4)
lines(tab$Thursday, col='green', lwd=4)
lines(tab$Friday, col='blue', lwd=4)
lines(tab$Saturday, col='purple', lwd=4)
legend("topleft",c('Monday', 'Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'), fill=c('red','orange','yellow','green','blue','purple','pink'))
dev.off()
```

```{r}

accidents$Year = format(as.Date(accidents$Date, format="%Y-%m-%d"),"%Y")
yeartab = table(accidents$Hour, accidents$Year)
yeartab = as.data.frame.matrix(yeartab) 

png("../Graphs & Images/Basic Layouts/AllAccidentsYearHourSplitExplained.png", width=10,height=6,units='in', res=600)
plot(yeartab$'2017', type="l", ylim=c(0,2500),col='blue', lwd=4, ylab="Number of Accidents", xlab="Hour of Day", xlim=c(.5,24.5), xaxt="none", yaxt="none",main="Accidents by Year and Hour")
axis(1, c(1,7,13,19,24), c(0,6,12,18,23),las="2")
axis(2,las="2")
lines(yeartab$'2018', col='green', lwd=4)
lines(yeartab$'2019', col='red', lwd=4)
lines(yeartab$'2019'*2, col='purple', lwd=4, type='b' )
legend("topleft",c('2017', '2018','2019 (Jan to June)', '2019 (Projected)'), fill=c('blue','green','red', 'purple'))
dev.off()

```

```{r}
accidents$Month = format(as.Date(accidents$Date, format="%Y-%m-%d"),"%B")
monthtab = table(accidents$Hour, accidents$Month)
monthtab = as.data.frame.matrix(monthtab) 
names(monthtab)


png("../Graphs & Images/Basic Layouts/AllAccidentsMonthHourSplit.png", width=10,height=6,units='in', res=600)
plot(monthtab$January, type="l", ylim=c(0,650),col='#469990', lwd=4, ylab="Number of Accidents", xlab="Hour of Day", xlim=c(.5,24.5), xaxt="none", yaxt="none",main="Accidents by Month and Hour")
axis(1, c(1,7,13,19,24), c(0,6,12,18,23),las="2")
axis(2,las="2")
lines(monthtab$Feburary, col='#42d4f4', lwd=4)
lines(monthtab$March, col='#4363d8', lwd=4)
lines(monthtab$April, col='#3cb44b', lwd=4)
lines(monthtab$May, col='#FF4340', lwd=4)
lines(monthtab$June, col='#ffe119', lwd=4)
lines(monthtab$July, col='#f58231', lwd=4)
lines(monthtab$August, col='green', lwd=4)
lines(monthtab$September, col='#aaffc3', lwd=4)
lines(monthtab$October, col='#00bee0', lwd=4)
lines(monthtab$November, col='purple', lwd=4)
lines(monthtab$December, col='pink',lwd=4)
legend("topleft",c("Jan","Feb","Mar","Apr","May", "June","July","Aug","Sep","Oct","Nov","Dec"), fill=c('#469990','#42d4f4','#4363d8','#3cb44b','#FF4340','#ffe119','#f58231','green','#aaffc3','#00bee0','purple','pink'))
dev.off()

```



```{r}
hourtab = table(accidents$Hour)
hourtab = as.data.frame(hourtab) 

png("../Graphs & Images/Basic Layouts/AllAccidentsHourSplit.png", width=10,height=6,units='in', res=600)
plot(hourtab$Freq, type="l", lwd=4, col="red", xaxt="none", yaxt="none", ylab="Number of Accidents", xlab="Hour of Day", main="Accidents by Hour")
axis(1, c(1,7,13,19,24), c(0,6,12,18,23),las="2")
axis(2,seq(0,5000, by= 1000), las="2")
dev.off()
```

```{r}
# accidents$NumMonth = format(as.Date(accidents$Date, format="%Y-%m-%d"),"%m")
# acc1718=accidents[which(accidents$Year !=2019),]
yearlymonthtab = table(accidents$NumMonth, accidents$Year, dnn = c("Month","Year"))
yearlymonthtab = as.data.frame(yearlymonthtab)
# 
yearlymonthtab$Freq[25:36]

plot(yearlymonthtab$Freq[0:12], type="l", ylim=c(1000,3000),col='blue', lwd=4, ylab="Number of Accidents", xlab="Month", xlim=c(.5,12.5), xaxt="none", yaxt="none",main="Accidents by Year and Month")
axis(1, seq(1,12,by=1), c("Jan","Feb","Mar","Apr","May", "June","July","Aug","Sep","Oct","Nov","Dec"),las="2")
axis(2,las="2")
lines(yearlymonthtab$Freq[13:24], col='green', lwd=4)
lines(yearlymonthtab$Freq[25:29], col='red', lwd=4)
```

