---
title: "test"
output: html_document
---

```{r}
library(feather)
weather = read_feather("/home/pete/Downloads/2017+2018 Weather Stage 2.feather")
min = min(weather$Unix)
max = max(weather$Unix)
weathersorted = weather[order(weather$Unix),]
head(weathersorted)
min 
max

length(weather$Date)

head(weather)

##Creating bins style table
br = seq(0,1,by=0.05)
ranges = paste(head(br,-1), br[-1], sep=" - ")
freq   = hist(weather$humidity, breaks=br, include.lowest=TRUE, plot=FALSE)
humidbins = data.frame(range = ranges, frequency = freq$counts)

total = sum(freq$counts)

##Record 17 is the one related to 80% humidity. The following code shows the percent of the records at or above 80% humidity
sum(freq$counts[17:20])/total
##Split data to only high humidity percentages. 
humidbins[c(17,18,19,20),]

humidbins
```

```{r}
library(feather)
oldweather = read_feather("/home/pete/Documents/GitHub/Ignore/Weather/2017+2018 Weather Full.feather")
head(oldweather)
typeof(oldweather$Date)
head(oldweather$Date)

library(anytime)
# oldweather$test <- anytime::anytime(oldweather$time)
oldweather$test <- as.POSIXct(oldweather$time, tz="UTC")  
# attributes(oldweather$test)$tzone <- "America/New_York"  

library(lubridate)
oldweather$time = with_tz(oldweather$test, "America/New_York")
oldweather$time

oldweather$test2
oldweather$hour = hour(oldweather$test2)

oldweather$Date = date(oldweather$test2)

head(oldweather)

drop= c("time", "test", "test2")
oldweather = oldweather[ , !(names(oldweather) %in% drop)]

oldweather$test = paste(oldweather$Date, oldweather$hour, sep = " ")

oldweather$Unix = as.numeric(as.POSIXct(oldweather$test, format="%Y-%m-%d %H"))

head(oldweather)

max(oldweather$Unix)

library(feather)
write_feather(oldweather, "/home/pete/Documents/GitHub/Ignore/Weather/2017+2018 Weather Unix.feather")
colnames(oldweather)[colnames(oldweather)=="ORIG_FID"] <- "Grid_Block"
```

##Adding weather to accident records
```{r}
accidents = read.csv("/home/pete/Documents/GitHub/SCAL_USIgnite-911/Excel & CSV Sheets/Accident Only Files/2017+2018 Accidents.csv")

accidentswithHum <- merge(accidents,oldweather,by=c("Unix","Grid_Block"))

colnames(accidentswithHum)

drop= c("Time", "icon", "Date.y", "summary", "id", "precipIntensity.y", "precipType")
accidentswithHum = accidentswithHum[ , !(names(accidentswithHum) %in% drop)]

write.csv(accidentswithHum, "/home/pete/Documents/GitHub/SCAL_USIgnite-911/Excel & CSV Sheets/Accident Only Files/2017+2018 Accidents.csv")

```

##Finding high humidity records
```{r}
numofrecords = length(highhum$humidity)

values = c(.80,.85, .90, .95, .98, .99, 1)
for(i in values){
print(i)
maxhum = i
highhum = with(accidentswithHum, accidentswithHum[(humidity >= maxhum ), ])
typeof(highhum$humidity)
numofrecords = length(highhum$humidity)
highhum = highhum[order(highhum$humidity),]

title = paste("Accidents - High Humidity", (maxhum*100), "%", numofrecords)
library(ggmap)
lats<-c(34.99, 35.15)
lons<-c(-85.4,-85.05)
par(mar = rep(0, 4))
bb<-make_bbox(lon=lons,lat=lats, f=0.05)
cda<-get_map(bb,zoom=13,maptype="roadmap", source='google')
map = ggmap(cda) +theme_minimal(base_size = 18) +
  labs(x="Longitude",y="Latitude", title= title ) +
  geom_point(aes(x=highhum$Center_Long, y=highhum$Center_Lat), data=highhum, color= 'red', alpha=.25, size=1.5)
print(map)
}
```


```{r}
library(feather)
weather19 = read_feather("/home/pete/Documents/GitHub/Ignore/Weather/2019 Weather.feather")

colnames(weather19)

typeof(weather19$time)
head(weather19)

## Unixof June 1 midnight - 1559361600
##Unix of June 21 11:59pm -  1561175940

begin = 1559361600
end = 1561175940

june = with(weather19, weather19[between(time, begin, end, incbounds=TRUE), ])
unique(june$Date)

keep= c("ORIG_FID", "Center_Lat","Center_Long","Date", "time", "timereadable", "apparentTemperature","temperature", "humidity", "icon", "summary")
june = june[ , (names(june) %in% keep)]

head(june)

colnames(june)[colnames(june)=="ORIG_FID"] <- "Grid_Block"

colnames(june)[colnames(june)=="timereadable"] <- "hour"
colnames(june)[colnames(june)=="hour"] <- "Hour"
colnames(june)[colnames(june)=="time"] <- "Unix"

colnames(june)[colnames(june)=="icon"] <- "Event"
colnames(june)[colnames(june)=="summary"] <- "Conditions"

colnames(june)[colnames(june)=="temperature"] <- "Temperature"

colnames(june)[colnames(june)=="apparentTemperature"] <- "ApparentTemperature"
colnames(june)[colnames(june)=="humidity"] <- "Humidity"


ordercols = c("Grid_Block","Center_Lat","Center_Long","Unix","Date","Hour", "Temperature", "ApparentTemperature", "Humidity", "Event", "Conditions")

june = june[, ordercols]

north = 35.05
south = 35.03
east = -85.259
west = -85.32
juneMLK = with(june, june[(between(Center_Lat, south, north, incbounds=TRUE)), ])
juneMLK = with(juneMLK, juneMLK[between(Center_Long, west, east, incbounds=TRUE), ])

grids = unique(junemlk$Grid_Block)

grids 
grids = grids[6:length(grids)]

test = dplyr::filter(junemlk, Grid_Block %in% grids)
test2 = with(test, test[between(Grid_Block, 125, 132, incbounds=TRUE), ])
head(test2)
# juneMLK = junemlk
library(ggmap)
lats<-c(35.025, 35.08)
lons<-c(-85.33,-85.25)
par(mar = rep(0, 4))
bb<-make_bbox(lon=lons,lat=lats, f=0.05)
cda<-get_map(bb,zoom=13,maptype="roadmap", source='google')
ggmap(cda) +theme_minimal(base_size = 18) + geom_point(aes(x=test2$Center_Long, y=test2$Center_Lat),data = test2,  color='red', alpha=.25, size=1.5)

write.csv(test2, "/home/pete/Documents/GitHub/Ignore/Weather/MLK June.csv")

```

